name: Blank Issue
description: Open a general issue
title: "[ISSUE]: "
labels: []

body:
  - type: markdown
    attributes:
      value: |
        ## General Issue

        This issue is created under **NSoC'26 (Nexus Spring of Code)**.
        If you are contributing through another open source event such as Apertre 3.0 or GSSoC'26, mention it here as well.
        If relevant, kindly consider assigning it to me.

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context